name: Create README based on data

on:
  push:
    branches:
      - main
    paths:
      - 'data/data.csv'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate README
        run: python ./scripts/create_readme.py

      - name: Commit and push
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          echo "Changes to commit"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated README"
          git push
    
