name: Update profile

on:
  push:
    branches:
      - main

jobs:
  sync:
    env:
      PROFILE_ACCESS_TOKEN: '${{ secrets.PROFILE_ACCESS_TOKEN }}'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          repository: anakin87/anakin87
          path: profile

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate profile README
        run: python ./scripts/update_profile.py

      - name: Commit and push
        run: |
          cd profile
          git config user.name ghactions
          git config user.email ghactions@github.com          
          git add .
          git commit -m "generated README"
          git push "https://ghactions:$PROFILE_ACCESS_TOKEN@github.com/anakin87/anakin87.git"