name: Update profile

on:
  push:
    branches:
      - main

jobs:
  sync:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          repository: anakin87/anakin87
          path: profile

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate profile README
        run: python ./scripts/update_profile.py

      - name: Pushes to profile repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PROFILE_ACCESS_TOKEN }}
        with:
          source-directory: 'profile'
          destination-github-username: 'anakin87'
          destination-repository-name: 'anakin87'
          user-name: github-actions
          target-branch: main